### ISSUE TITLE
DIGIT Works Feedback

### ISSUE THREAD

**Issue by gak5275** [JiayuanWen/Belloc-More-Beasts#30]
This is where we can put feedback from our DIGIT Works presentation.

**Comment by Stach13** [comment]
I thought your collection of images through XSLT was really good as well as categorizing each set of text. The images show great visual interpretations of what the poems described.

**Comment by tylerakam** [comment]
I really liked the styling of the site! It looked like it was sort of hand-drawn like the images you guys had to work with. That was my favorite part of it, being able to see how it matches the source material. Some things that could maybe be improved though, are the image integration. I noticed that when I hover over an image, it flips it, making the text harder to read. Maybe just make those images bigger when hovered on? Apart from that, the gallery seems a little unorganized, but in general it's nice to have that kind of page for people to look at! The source documents were wonderfully organized in a table and linked really well. Overall, it's a great site!

**Comment by JaxAbele** [comment]
I thought the organization of this project was super impressive. Especially your table of contents and how several different elements in your full text section are color coded. Very user friendly. I noticed while scrolling through the gallery that some of the pictures would flip over to face the other side of the screen after scrolling to a certain point. If i have to make a suggestion, I would just try to find a way to keep those still while scrolling through.

**Comment by luh429** [comment]
I really thought your project was interesting. I loved how you included so many of the pictures and illustrations on each page, it really brought the project to life. I also thought your sight looked very organized. Everything was very crisp and clean.

**Comment by epp5198** [comment]
This project was very interesting, the website build looks amazing along with all the the photos. The color coding of the text with the legend is very useful and adds that extra element to the text.

**Comment by erinmooney** [comment]
First of all, great work. The nav bar buttons are great, and the background color is a nice, neutral color that allows for a lot of wiggle-room with the color of the text (changing based on xml) and the images. 

I would recommend changing the yellow/orange text color for subjects to change to another color. It is a little hard to read, so changing it will make this site more accessibility friendly. 

Overall, great job!

**Comment by gzc5211** [comment]
I think the hand-drawn picture really catches my eye, and the layout for the page is easy to read and find the thing I'm looking for.  Also, the about page and other things did a nice job.

**Comment by gvt5036** [comment]
I really enjoyed viewing this site. Everything works as it should, it's simple and pleasing to the eye. I really like that you added a link to the Github repo! I only noticed two real areas of improvement, and that's in some of the use of color. I noticed you used color to represent certain words on the page, which is a great idea to point out specific things you want to draw attention to, but I would maybe reconsider the color palate as some of the colors make things difficult/jarring to read. The other thing I noticed is that when switching pages, the screen flashes cyan for a second, which might have just been my browser but it was certainly jarring.

**Comment by kzp308** [comment]
I really liked looking through the website and checking out what you guys have been working on! I like the little hand that shows up when you mouse over the nav bar. The home page is also very neatly done. I think one thing I would change is the image sizing on the gallery page. They're really big but nothing some CSS can't fix! Overall, great site!
