### ISSUE TITLE
Things to do (According to Dr. B)

### ISSUE THREAD

**Issue by gak5275** [JiayuanWen/Belloc-More-Beasts#4]
Here are some of the next steps we need to take for our project:

- Take screenshots of all of the pictures in the book and put them in a folder, with a consistent naming scheme. Eventually, it must be possible to reference the pics in both XML and HTML.
- Begin coding the book in XML (including descriptions/interpretations of the pictures)
- Include links on our repo (in the README file) and our website to the [book's website](https://www.gutenberg.org/cache/epub/27176/pg27176-images.html)
- Include a link to our repo on our website

As of right now, the XML should take priority over the website. I think that we learn how to integrate the two of them later in the class.

**Comment by ebeshero** [comment]
About beginning to encode the book: My recommendation is that each of you takes at least one poem from the book, and each poem goes in its own separate file.

Why? It will be easier to resolve merge issues (even in a branched GitHub repo) if each of you works with separate XML files. We can write XSLT code in a few weeks that takes a collection (a folder) of separate XML files and assembles them in one file if we want to do that.

This means you may want to include the page numbers or numbering from the book within your distinct files (maybe as a self-closing element like `<pb n="5"/>` to help give a clue about the order of the poems in the book. 

Don't worry about the title page encoding yet. Concentrate on the individual poems and how to encode the images and footnotes.

Each of you should be on assignment to encode at least one or two poems + associated figures from the book for the next milestone.

**Comment by ebeshero** [comment]
With the pictures available each in their own separate screenshot,  let's think about a consistent filenaming system. You want to make it easy for someone to point to the image file from the poem they are coding. So for the poem titled "The Python" and its series of images, perhaps we can name those images like this?

python-1.jpg

python-2.jpg

python-3.jpg

etc.

Does that make sense?
